/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { NativeModules } from 'react-native';
import Instana from 'react-native-instana-eum';
console.warn(Instana);
console.warn(NativeModules);

export default class App extends Component {
  componentDidMount() {
    Instana.setup(YOUR_INSTANA_REPORTING_URL, YOUR_INSTANA_APP_KEY);
    Instana.setUserName('Nils Mustermann');
    Instana.setView('MainView');
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Monitored by Instana.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
