/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View, SafeAreaView, Button } from 'react-native';
import { NativeModules } from 'react-native';
import Instana from 'react-native-instana-eum';
console.warn(Instana);
console.warn(NativeModules);

export default class App extends Component {
  componentDidMount() {
    Instana.setup(YOUR_INSTANA_APP_KEY, YOUR_INSTANA_REPORTING_URL);
    Instana.setUserID('123456');
    Instana.setUserEmail('nils@example.com');
    Instana.setUserName('Nils Mustermann');
    Instana.setMeta('randomKey', 'randomValue');
    Instana.setView('MainView');
    
    getSessionID();
    async function getSessionID() {
      try {
        var sessionID = await Instana.getSessionID();
      } catch (e) {
        console.error(e);
      }
    }

    setIgnoreURLsByRegex();
    async function setIgnoreURLsByRegex() {
      try {
        await Instana.setIgnoreURLsByRegex(["http:\/\/localhost:8081.*", "example.com", "["]);
      } catch (e) {
        console.warn(e);
      }
    }
  }


  async onRunFetchAsync() {
    try {
      let response = await fetch('https://reactnative.dev/movies.json');
      let json = await response.json()
      console.log('success', json);
    } catch (error) {
      console.warn(error);
    }
  }

  async onRunXMLHttpRequest() {
    var request = new XMLHttpRequest();
    request.onreadystatechange = (e) => {
      if (request.readyState !== 4) {
        return;
      }

      if (request.status === 200) {
        console.log('success', request.responseText);
      } else {
        console.warn('error');
      }
    };

    request.open('GET', 'https://reactnative.dev/movies.json');
    request.send();
  }

  render() {
    return (
      <SafeAreaView style={styles.container}>
        <View>
        <Button
          onPress={this.onRunFetchAsync}
          title="Run `fetch`"
        />
        </View>
        <View  style={{marginTop:10}}>
        <Button
          onPress={this.onRunXMLHttpRequest}
          title="Run `XMLHttpRequest`"
        />
        </View>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});
